project_id = "gdcxtefbarvnrtvacqln"

[functions.check-medication-alerts]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.send-user-invitation]
verify_jwt = true

[functions.notify-transportation-events]
verify_jwt = false

[functions.send-event-notifications]
verify_jwt = false
