project_id = "gdcxtefbarvnrtvacqln"

[functions.check-medication-alerts]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.send-user-invitation]
verify_jwt = true

[functions.notify-transportation-events]
verify_jwt = false

[functions.send-event-notifications]
verify_jwt = false

[functions.send-bulk-email]
verify_jwt = true

[functions.send-incident-notification]
verify_jwt = false

[functions.send-health-center-notification]
verify_jwt = false

[functions.send-user-approval-notification]
verify_jwt = false
