// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Parse tokens from the URL on load (recovery links, magic links, OAuth return).
    detectSessionInUrl: true,
    // PKCE requires the same browser that clicked "Forgot password" to hold code_verifier.
    // Emails are often opened on another device → exchange fails and updateUser says session missing.
    // Implicit flow uses hash tokens in the link; works for password reset across devices.
    flowType: "implicit",
  }
});